const featureIds=['crosswordPanel','readingPanel','picturesPanel','progressPanel'];
function showFeature(name){const ids={crossword:'crosswordPanel',reading:'readingPanel',pictures:'picturesPanel',progress:'progressPanel'};document.getElementById(ids[name]).scrollIntoView({behavior:'smooth',block:'start'});}
function clueFor(w){const clues={AGUA:'Líquido que necesitamos para vivir.',RIO:'Corriente natural de agua.',PALTA:'Fruto verde que se cultiva en el valle.',LUCUMA:'Fruta de pulpa anaranjada y dulce.',PLANTA:'Ser vivo que puede tener raíz, tallo y hojas.',SEMILLA:'Parte de la planta que puede germinar.',RAIZ:'Parte de la planta que suele estar bajo la tierra.',TALLO:'Sostiene las hojas y flores de una planta.',HOJA:'Parte de la planta que capta la luz.',FLOR:'Parte colorida de algunas plantas.',FRUTO:'Parte que contiene o protege las semillas.',SOL:'Estrella que nos da luz y calor.',AIRE:'Mezcla de gases que respiramos.',SUELO:'Capa de tierra donde crecen las plantas.',RESPETO:'Valor que nos ayuda a convivir.',FAMILIA:'Personas unidas por parentesco y cariño.',ESCUELA:'Lugar donde aprendemos.',LECTURA:'Actividad de comprender un texto escrito.',CUENTO:'Narración breve con personajes.',VERBO:'Palabra que expresa acción o estado.',SUSTANTIVO:'Palabra que nombra personas, animales, lugares o cosas.',ADJETIVO:'Palabra que expresa una característica.',SUMA:'Operación matemática de juntar cantidades.',RESTA:'Operación para quitar o hallar la diferencia.',FRACCION:'Representa una o varias partes de un entero.',DECIMAL:'Número que puede escribirse con coma decimal.',PERIMETRO:'Medida del contorno de una figura.',ECOSISTEMA:'Seres vivos y el ambiente donde interactúan.',ATMOSFERA:'Capa de gases que rodea la Tierra.',OZONO:'Gas que ayuda a protegernos de radiación ultravioleta.',RECICLAR:'Transformar residuos para volver a utilizarlos.',HUAICO:'Flujo de lodo y piedras que baja por una quebrada.',COSECHA:'Recolección de los productos cultivados.',CHACRA:'Terreno donde se cultivan plantas.'};return clues[w]||`Palabra del tema «${topic}». Escucha su pronunciación y recuerda lo aprendido.`}
function makeCrossword(){const words=game.words.slice(0,8);$('crosswordClues').innerHTML='';words.forEach((w,i)=>{const d=document.createElement('div');d.className='cross-item';const l=document.createElement('label');l.textContent=(i+1)+'. '+clueFor(w);l.htmlFor='cw'+i;const inp=document.createElement('input');inp.id='cw'+i;inp.dataset.answer=w;inp.autocomplete='off';inp.placeholder='Escribe la palabra';const b=document.createElement('button');b.textContent='🔊';b.type='button';b.onclick=()=>speak([w]);d.append(l,inp,b);$('crosswordClues').append(d)});$('crosswordFeedback').textContent=''}
$('checkCrossword').onclick=()=>{let inputs=[...document.querySelectorAll('#crosswordClues input')],ok=0;inputs.forEach(i=>{let yes=norm(i.value)===i.dataset.answer;i.style.borderColor=yes?'#16a34a':'#ef4444';if(yes)ok++});$('crosswordFeedback').textContent=`Resultado: ${ok} de ${inputs.length} palabras correctas.`;if(ok===inputs.length)recordProgress('Crucigrama',ok,inputs.length)};
$('listenCrossword').onclick=()=>speak([...document.querySelectorAll('#crosswordClues input')].map(i=>clueFor(i.dataset.answer)));$('newCrossword').onclick=makeCrossword;
const storyBank={III:{title:'La fruta de Pocor',text:'En Pocor, una familia cuida sus plantas. Cada mañana observa la tierra y riega con cuidado. En la chacra crecen paltas y lúcumas. La familia recoge solo los frutos maduros y evita desperdiciar el agua.',questions:[['¿Qué cuida la familia?',['Sus plantas','Un barco','Un avión'],0],['¿Qué recurso usan con cuidado?',['Agua','Petróleo','Humo'],0]]},IV:{title:'Una chacra responsable',text:'Los estudiantes de Pocor visitaron una chacra del Valle Fortaleza. Observaron las raíces, los tallos y las hojas de las plantas. El agricultor explicó que el riego responsable ayuda a ahorrar agua y que el suelo necesita cuidados para producir buenos frutos.',questions:[['¿Qué observaron los estudiantes?',['Partes de las plantas','Planetas','Máquinas del mar'],0],['¿Por qué es importante el riego responsable?',['Para ahorrar agua','Para inundar la chacra','Para desperdiciar agua'],0]]},V:{title:'Guardianes del Valle Fortaleza',text:'En el Valle Fortaleza, el agua y el suelo son recursos esenciales para la agricultura. Un grupo de estudiantes propuso reutilizar materiales, no quemar residuos y cuidar los canales de riego. Comprendieron que las pequeñas acciones de la comunidad pueden proteger la biodiversidad y mejorar el ambiente.',questions:[['¿Qué propone el grupo?',['Cuidar los recursos','Quemar residuos','Desperdiciar agua'],0],['¿Qué idea principal comunica el texto?',['La comunidad puede proteger el ambiente','La agricultura no necesita agua','Los residuos deben quemarse'],0]]}};
function makeReading(){const st=storyBank[cycle];$('readingLevel').textContent=`${labels[cycle]} · ${area} · ${topic}`;$('readingText').innerHTML='<h3>'+st.title+'</h3><p>'+st.text+'</p>';$('readingQuestions').innerHTML='';st.questions.forEach((q,i)=>{const box=document.createElement('div');box.className='cross-item';const p=document.createElement('p');p.textContent=(i+1)+'. '+q[0];box.append(p);q[1].forEach((op,j)=>{const lab=document.createElement('label');lab.style.display='block';const r=document.createElement('input');r.type='radio';r.name='rq'+i;r.value=j;lab.append(r,document.createTextNode(' '+op));box.append(lab)});$('readingQuestions').append(box)});$('readingFeedback').textContent=''}
$('readAloud').onclick=()=>speak([$('readingText').innerText]);
$('readSlow').onclick=()=>{if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('readingText').innerText);u.lang='es-PE';u.rate=.65;window.speechSynthesis.speak(u)};
$('readingQuestions').addEventListener('change',()=>{const qs=storyBank[cycle].questions;let correct=0,answered=0;qs.forEach((q,i)=>{const sel=document.querySelector(`input[name="rq${i}"]:checked`);if(sel){answered++;if(Number(sel.value)===q[2])correct++}});if(answered===qs.length){$('readingFeedback').textContent=`Comprensión lectora: ${correct} de ${qs.length} respuestas correctas.`;if(correct===qs.length)recordProgress('Lectura',correct,qs.length)}});
const emojis={AGUA:'💧',RIO:'🏞️',PALTA:'🥑',LUCUMA:'🟠',FRUTA:'🍎',PLANTA:'🪴',SEMILLA:'🌱',RAIZ:'🌿',TALLO:'🌱',HOJA:'🍃',FLOR:'🌼',SOL:'☀️',AIRE:'💨',SUELO:'🌎',FAMILIA:'👨‍👩‍👧',ESCUELA:'🏫',LIBRO:'📚',GATO:'🐈',PATO:'🦆',VACA:'🐄',PERRO:'🐕',MAIZ:'🌽',COSECHA:'🧺',CHACRA:'🚜',RECICLAR:'♻️',OZONO:'🌤️',ATMOSFERA:'🌍',HUAICO:'⛰️',SUMA:'➕',RESTA:'➖',FRACCION:'🍕',DECIMAL:'🔢',RESPETO:'🤝',LECTURA:'📖',CUENTO:'📘',VERBO:'✍️',SUSTANTIVO:'🔤',ADJETIVO:'✨'};
function makePictures(){const words=shuffle(game.words).slice(0,6);$('pictureCards').innerHTML='';words.forEach((w,i)=>{const card=document.createElement('div');card.className='picture-card';const pic=document.createElement('div');pic.className='pic';pic.textContent=emojis[w]||'🧩';const label=document.createElement('p');label.textContent='Imagen '+(i+1);const sel=document.createElement('select');sel.dataset.answer=w;sel.innerHTML='<option value="">Elige una palabra…</option>'+shuffle(words).map(x=>`<option value="${x}">${x}</option>`).join('');card.append(pic,label,sel);$('pictureCards').append(card)});$('pictureFeedback').textContent=''}
$('checkPictures').onclick=()=>{const sels=[...document.querySelectorAll('#pictureCards select')];let ok=0;sels.forEach(s=>{const yes=s.value===s.dataset.answer;s.style.borderColor=yes?'#16a34a':'#ef4444';if(yes)ok++});$('pictureFeedback').textContent=`¡Has acertado ${ok} de ${sels.length}!`;if(ok===sels.length)recordProgress('Imágenes',ok,sels.length)};$('speakPictures').onclick=()=>speak([...document.querySelectorAll('#pictureCards select')].map(s=>s.dataset.answer));
function readProgress(){try{return JSON.parse(localStorage.getItem('pupiletrasProgress')||'[]')}catch(e){return []}}
function readStudents(){try{return JSON.parse(localStorage.getItem('pupiletrasStudents')||'[]')}catch(e){return []}}
function currentStudent(){return localStorage.getItem('pupiletrasCurrentStudent')||''}
function selectedGrade(){return localStorage.getItem('pupiletrasCurrentGrade')||$('studentGrade')?.value||'1.º'}
function saveCurrentStudent(){const name=$('studentName').value.trim().replace(/\s+/g,' ');const grade=$('studentGrade').value;if(!name){$('studentFeedback').textContent='Escribe el nombre del estudiante antes de guardar.';return}const students=readStudents();const key=name.toLocaleLowerCase('es-PE')+'|'+grade;const found=students.find(s=>s.key===key);if(!found)students.push({key,name,grade});localStorage.setItem('pupiletrasStudents',JSON.stringify(students));localStorage.setItem('pupiletrasCurrentStudent',name);localStorage.setItem('pupiletrasCurrentGrade',grade);$('studentFeedback').textContent='Estudiante seleccionado: '+name+' · '+grade;renderStudentOptions();renderProgress()}
function renderStudentOptions(){const sel=$('reportStudent');if(!sel)return;const old=sel.value;const students=readStudents();sel.innerHTML='<option value="">Todos los estudiantes</option>'+students.map(s=>`<option value="${s.key}">${s.name} · ${s.grade}</option>`).join('');if([...sel.options].some(o=>o.value===old))sel.value=old;if($('studentName')&&currentStudent())$('studentName').value=currentStudent();if($('studentGrade')&&localStorage.getItem('pupiletrasCurrentGrade'))$('studentGrade').value=localStorage.getItem('pupiletrasCurrentGrade')}
function recordProgress(kind,score,total){const arr=readProgress();arr.push({date:new Date().toLocaleDateString('es-PE'),student:currentStudent()||'Sin registrar',grade:selectedGrade(),cycle,area,topic,kind,score,total,percent:total?Math.round(score/total*100):0});localStorage.setItem('pupiletrasProgress',JSON.stringify(arr));renderProgress()}
function filteredProgress(){let arr=readProgress();const student=$('reportStudent')?.value||'',areaFilter=$('reportArea')?.value||'',cycleFilter=$('reportCycle')?.value||'';if(student){const st=readStudents().find(s=>s.key===student);arr=arr.filter(x=>x.student===(st?.name||'')&&x.grade===(st?.grade||''))}if(areaFilter)arr=arr.filter(x=>x.area===areaFilter);if(cycleFilter)arr=arr.filter(x=>x.cycle===cycleFilter);return arr}
function renderProgress(){const root=$('progressSummary');if(!root)return;const arr=filteredProgress();root.innerHTML='';if(!arr.length){root.textContent='No hay actividades para mostrar con estos filtros. Selecciona un estudiante y completa una actividad.';return}const count=arr.length,correct=arr.reduce((n,x)=>n+(Number(x.score)||0),0),total=arr.reduce((n,x)=>n+(Number(x.total)||0),0),avg=total?Math.round(correct/total*100):0;const summary=document.createElement('div');summary.className='progressrow';summary.innerHTML=`<span class="stat">📝 ${count} actividades</span><span class="stat">🎯 ${avg}% de aciertos</span><span class="stat">👧🧒 ${new Set(arr.map(x=>x.student).filter(x=>x&&x!=='Sin registrar')).size} estudiantes</span>`;root.append(summary);const table=document.createElement('table');table.className='scoretable';table.innerHTML='<thead><tr><th>Fecha</th><th>Estudiante</th><th>Grado</th><th>Ciclo</th><th>Área</th><th>Actividad</th><th>Tema</th><th>Resultado</th></tr></thead>';const tb=document.createElement('tbody');arr.slice(-100).reverse().forEach(x=>{const tr=document.createElement('tr');[x.date,x.student||'Sin registrar',x.grade||'—',x.cycle,x.area,x.kind,x.topic,`${x.score}/${x.total} (${x.percent??(x.total?Math.round(x.score/x.total*100):0)}%)`].forEach(v=>{const td=document.createElement('td');td.textContent=v??'';tr.append(td)});tb.append(tr)});table.append(tb);root.append(table)}
function exportProgressCSV(){const arr=filteredProgress();if(!arr.length){alert('No hay resultados para descargar con los filtros seleccionados.');return}const rows=[['Fecha','Estudiante','Grado','Ciclo','Área','Actividad','Tema','Puntaje','Total','Porcentaje'],...arr.map(x=>[x.date,x.student||'Sin registrar',x.grade||'',x.cycle,x.area,x.kind,x.topic,x.score,x.total,x.percent??(x.total?Math.round(x.score/x.total*100):0)])];const csv='\ufeff'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='reporte_pupiletras.csv';document.body.append(a);a.click();a.remove();URL.revokeObjectURL(url)}
$('saveStudent')?.addEventListener('click',saveCurrentStudent);['reportStudent','reportArea','reportCycle'].forEach(id=>$(id)?.addEventListener('change',renderProgress));$('exportCSV')?.addEventListener('click',exportProgressCSV);$('printReport')?.addEventListener('click',()=>window.print());
$('clearProgress').onclick=()=>{if(confirm('¿Borrar todo el historial de actividades guardado en este dispositivo?')){localStorage.removeItem('pupiletrasProgress');renderProgress()}};
function printWorksheet(){$('printTopic').textContent=`${cycle} ciclo · ${area} · ${topic}`;window.print()}
